SELECT DISTINCT 
    AI.description,
    AI.INVOICE_AMOUNT,
    AI.INVOICE_ID,
    AC.payment_id AS Sender_reference,
    AI.INVOICE_CURRENCY_CODE, 
    AI.INVOICE_NUM,
    AC.CHECK_NUMBER,
    AC.CHECK_DATE,
    AC.VENDOR_NAME,
    AC.BANK_ACCOUNT_NAME AS SOURCE_BANK,
    AC.BANK_ACCOUNT_NUM AS SOURCE_ACCT,
    IEBA.BANK_ACCOUNT_NAME,
    IEBA.bank_account_num,
    AC.attribute9,
    CBBV.BANK_NAME,
    CASE
        WHEN fn.USER_NAME IN ('BMBURU', 'GMANDA') THEN 'MADEMOYE'
        ELSE fn.USER_NAME
    END AS USER_NAME
FROM 
    AP_SUPPLIERS ASP,
    AP_INVOICES_ALL AI,
    AP_INVOICE_PAYMENTS_ALL AIP,
    AP_SUPPLIER_SITES_ALL ASA,
    AP_CHECKS_ALL AC,
    IBY_EXTERNAL_PAYEES_ALL IEPAYEES,
    IBY_PMT_INSTR_USES_ALL IPIUA,
    IBY_EXT_BANK_ACCOUNTS IEBA,
    CE_BANK_BRANCHES_V CBBV,
    CE_BANK_ACCT_USES_ALL CBAU,
    IBY_ACCOUNT_OWNERS IAOWNERS,
    HR_OPERATING_UNITS HOU,
    AP_WFAPPROVAL_HISTORY_V APW,
    FND_USER fn
WHERE 
    IAOWNERS.EXT_BANK_ACCOUNT_ID = IEBA.EXT_BANK_ACCOUNT_ID
    AND AI.VENDOR_ID = ASP.VENDOR_ID
    AND AIP.INVOICE_ID = AI.INVOICE_ID
    AND AC.CHECK_DATE BETWEEN NVL(:FROM_DATE, AC.CHECK_DATE) AND NVL(:TO_DATE, AC.CHECK_DATE)
    AND AI.INVOICE_NUM = NVL(:P_invoice_num, AI.INVOICE_NUM)
    AND ASA.VENDOR_ID = AI.VENDOR_ID
    AND AIP.CHECK_ID = AC.CHECK_ID
    AND IAOWNERS.EXT_BANK_ACCOUNT_ID = IPIUA.INSTRUMENT_ID
    AND IEPAYEES.EXT_PAYEE_ID = IPIUA.EXT_PMT_PARTY_ID
    AND IEPAYEES.PAYEE_PARTY_ID = IAOWNERS.ACCOUNT_OWNER_PARTY_ID
    AND IEPAYEES.SUPPLIER_SITE_ID = ASA.VENDOR_SITE_ID
    AND ASA.VENDOR_ID = ASP.VENDOR_ID
    AND IEBA.BRANCH_ID = CBBV.BRANCH_PARTY_ID(+)
    AND IEBA.EXT_BANK_ACCOUNT_ID = AI.EXTERNAL_BANK_ACCOUNT_ID
    AND HOU.ORGANIZATION_ID = ASA.ORG_ID
    AND fn.USER_ID = AI.CREATED_BY;

